chat/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:chatroom_id>/', views.detail, name='detail'),
    path('qna/create/<int:chatroom_id>', views.qna_create, name='qna_create'),
    path("qna_create_ajax/<int:chatroom_id>/", csrf_exempt(views.qna_create), name="qna_create_ajax"),
    path('chatroom/create/', views.chatroom_create, name='chatroom_create'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name ='common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User

class Chatroom(models.Model):
    title = models.CharField(max_length=5)
    create_date = models.DateTimeField()
    mbti = models.CharField(max_length=4)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class Qna(models.Model):
    chatroom = models.ForeignKey(Chatroom, on_delete=models.CASCADE)
    question = models.TextField()
    answer = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField()

common/models.py
from django.db import models

# Create your models here.

chat/forms.py
from django import forms
from .models import Chatroom

class ChatroomForm(forms.ModelForm):
    MBTI_CHOICES = (
        ('ISTJ', 'ISTJ'),
        ('INTP', 'INTP'),
        ('ENFP', 'ENFP'),
        ('ENTJ', 'ENTJ'),
    )
    mbti = forms.ChoiceField(choices=MBTI_CHOICES)
    
    class Meta:
        model = Chatroom
        fields = ['title', 'mbti']

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")
    
    class Meta:
        model = User
        fields = ("first_name", "last_name", "username", "password1", "password2", "email")

chat/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Chatroom, Qna
from chat.gpt import gpt_prompt
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .forms import ChatroomForm




@login_required(login_url='common:login')
def index(request):
    chatroom_list = Chatroom.objects.filter(user=request.user).order_by('-create_date')
    context = {'chatroom_list': chatroom_list}
    return render(request, 'chat/chatroom_list.html', context)

@login_required(login_url='common:login')
def detail(request, chatroom_id):
    chatroom = get_object_or_404(Chatroom.objects.filter(user=request.user), pk=chatroom_id)
    context = {'chatroom': chatroom}
    return render(request, 'chat/chatroom_detail.html', context)


@csrf_exempt
@login_required(login_url='common:login')
def qna_create(request, chatroom_id):
    if request.method == "POST":
        chatroom = get_object_or_404(Chatroom, pk=chatroom_id)
        user = request.user
        qna_count = Qna.objects.filter(chatroom_id=chatroom.id).count()
        latest_qnas = Qna.objects.filter(chatroom_id=chatroom.id).order_by('-create_date')[:min(qna_count, 4)]
        qna_pairs = [(qna.question, qna.answer) for qna in latest_qnas]
        question = request.POST.get('question')
        answer = gpt_prompt(question, chatroom.title, chatroom.mbti, qna_pairs, user.last_name)
        qna = Qna(chatroom=chatroom, question=question, answer=answer, create_date=timezone.now(), user=user)
        qna.save()

        # JSON 형식으로 반환
        return JsonResponse({"answer": answer})
    else:
        return JsonResponse({"error": "Invalid request method"}, status=400)
    

@login_required(login_url='common:login')
def chatroom_create(request):
    if request.method == 'POST':
        form = ChatroomForm(request.POST)
        if form.is_valid():
            chatroom = form.save(commit=False)
            chatroom.user = request.user  # user 속성에 로그인 계정 저장
            chatroom.create_date = timezone.now()
            chatroom.save()
            return redirect('chat:index')
    else:
        form = ChatroomForm()
    context = {'form': form}
    return render(request, 'chat/chatroom_form.html', context)

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(first_name=first_name, last_name=last_name, username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

config/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse





def index(request):

    return render(request, 'main.html')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="shortcut icon" href="{% static '/favicon.ico' %}">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>MBTIGPT</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
    
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/chat/chatroom_detail.html
{% extends 'base.html' %}
{% block content %}



<div class="detail_body">
    <h3>{{ chatroom.title }} [{{ chatroom.mbti }}]</h3>
<div id="chatroom" class="chatroom">
    {% for qna in chatroom.qna_set.all %}
    <div class="chat">
        <div class="question_bubble">
            {{ qna.question }}
        </div>
        <div class="answer_bubble" id="answerBubble{{ forloop.counter }}">
            {{ qna.answer }}
        </div>
    </div>
    {% endfor %}
</div>

<form class="submit_form" onsubmit="submitQuestionForm();">
    {% csrf_token %}
    <textarea name="question" id="question" rows="1" placeholder="고민을 입력해보세요!"></textarea>
    <button type="submit" class="submit_button">&gt;</button>
</form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function submitQuestionForm() {
        let chatroom = document.getElementById("chatroom");
        let question = document.getElementById("question").value;
        let questionBubble = document.createElement("div");
        let answerBubble = document.createElement("div");
        let chat = document.createElement("div");

        chatroom.appendChild(chat);
        chat.className = "chat";
        chat.appendChild(questionBubble);
        chat.appendChild(answerBubble);

        questionBubble.innerText = question;
        questionBubble.className = "question_bubble";


        window.scrollTo(0, document.body.scrollHeight);

        fetchAnswer(question, function (answer) {
            setTimeout(function () {
                answerBubble.innerText = answer;
                answerBubble.className = "answer_bubble";
                window.scrollTo(0, document.body.scrollHeight);
            }, 1500);
        });


        document.getElementById("question").value = "";
        event.preventDefault();
    }

    function fetchAnswer(question, callback) {
        $.ajax({
            url: "{% url 'chat:qna_create_ajax' chatroom.id %}",
            method: "POST",
            data: {
                question: question,
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function (response) {
                callback(response['answer']);
            }
        });
    }

    document.addEventListener('DOMContentLoaded', function () {
        var questionElement = document.getElementById('question');

        questionElement.addEventListener('keydown', function (event) {
            var keyCode = event.keyCode || event.which;

            if (event.shiftKey && keyCode === 13) {
                event.preventDefault();
                var selectionStart = questionElement.selectionStart;
                var selectionEnd = questionElement.selectionEnd;
                var value = questionElement.value;

                questionElement.value = value.slice(0, selectionStart) + '\n' + value.slice(selectionEnd);
                questionElement.selectionEnd = selectionStart + 1;
            } else if (keyCode === 13) {
                event.preventDefault();
                document.querySelector('.submit_button').click();
                questionElement.style.height = 'auto';
            }
        });

        questionElement.addEventListener('input', function (event) {
            questionElement.style.height = 'auto';
            questionElement.style.height = (questionElement.scrollHeight) + 'px';
        });
    });
</script>
{% endblock %}

templates/chat/chatroom_form.html
{% extends 'base.html' %}
{% block content %}
<div class="chatroom-form">
    <form method="post" class="form-centered">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">친구 이름은? </label>
            <input type="text" name="title" id="id_title" required>
        </div>
        <div class="radio-group">
            <div class="radio-group"> {% for mbti, label in form.mbti.field.choices %} <input type="radio"
                    id="{{ mbti }}" name="mbti" value="{{ mbti }}" {% if forloop.first %}checked{% endif %} required>
                <label for="{{ mbti }}">{{ label }}</label> {% endfor %} </div>
        </div> <input type="submit" value="친구 사귀기">
    </form>
</div>
<style scoped>
    /* 채팅방 폼 */
    .chatroom-form {
        /* display:flex; */
        width: 100%;
        max-width: 400px;
        padding-top: 70px;
        margin: 0 auto;
        font-family: Arial, Helvetica, sans-serif;
    }

    .form-group {
        display: flex;
        margin: 0 auto;
        align-items: center;
        width: 180px;
        font-size: 30px;
    }

    .form-group label {
        flex: 0 0 110px;
    }

    .form-group input[type="text"] {
        flex: 1;
        /* 나머지 공간 모두 사용 */
        width: 60px;
    }


    .chatroom-form label {
        display: block;
        font-size: 18px;
        color: #ccc;
        margin-bottom: 5px;
    }

    .chatroom-form input[type="text"] {
        width: 80%;
        height: 40px;
        border: 1px solid #555;
        border-radius: 5px;
        background-color: #222;
        color: #fff;
        font-size: 20px;
    }

    .chatroom-form input[type="submit"] {
        width: 60%;
        height: 40px;
        /* padding: 0 10px; */
        border: none;
        border-radius: 3px;
        background-color: #FF5347;
        color: #fff;
        font-size: 16px;
        font-weight: bold;
        cursor: pointer;
        margin-top: 20px
    }

    .form-centered {
        display: flex;
        flex-direction: column;
        align-items: center;
        /* 가운데 정렬 */
    }

    .chatroom-form input[type="submit"]:hover {
        background-color: #ff5347ec;
    }

    .chatroom-form_error {
        color: #949090;
    }

    /* 라디오 버튼 스타일링 */
    .radio-group {
        display: flex;
        justify-content: center;
        margin: 10px;
    }

    .radio-group label {
        display: block;
        width: 60px;
        height: 40px;
        line-height: 40px;
        border: 2px solid #555;
        border-radius: 3px;
        text-align: center;
        color: #fff;
        background-color: #222;
        cursor: pointer;
        margin: 10px;
        /* 라디오 버튼 사이에 10px 간격 추가 */
    }

    .radio-group input[type="radio"] {
        display: none;
    }

    .radio-group input[type="radio"]:checked+label {
        background-color: #FF5347;
    }
</style> {% endblock %}

templates/chat/chatroom_list.html
{% extends 'base.html' %}
{% block content %}

<div class="list_body">
<div class="friend">
    <h3><a href="{% url 'chat:chatroom_create' %}">새 친구를 찾아보자</a></h3>
</div>

{% if chatroom_list %}
<div class="chatroom_list">
    {% for chatroom in chatroom_list %}
    <div class="chatroom_item">
        <a href="{% url 'chat:detail' chatroom.id %}">{{ chatroom.title }} [{{ chatroom.mbti }}]</a>
    </div>
    {% endfor %}
</div>
{% else %}
<p>채팅방이 없습니다.</p>
{% endif %}
</div>

<style scoped>
    .list_body {
        display: flex;
        flex-direction: column;
        align-items: center;
    }

    .friend {
        display: flex;
        text-align: center;
        flex-direction: column;
        gap: 12px;
        margin-top: 30px;
        font-size: 18px;
        width: 250px;
        border-radius: 12px;
        background-color: #FF5346;
        margin-bottom: 20px;
    }
    .friend:hover {
        transform: scale(1.03);
    }
    
    .chatroom_list {
        display: flex;
        text-align: center;
        flex-direction: column;
        gap: 12px;
        padding: 20px;
        font-size: 17px;
        width: 300px;
    }
    
    .chatroom_item {
        background-color: #476FFF;
        padding: 12px;
        border-radius: 12px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        transition: transform 0.1s;
    }
    
    .chatroom_item a {
        text-decoration: none;
        color: #FFF;
    }
    
    .chatroom_item:hover {
        transform: scale(1.03);
    }
    
</style>

{% endblock %}

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<form class="sign-form" method="post" action="{% url 'common:login' %}">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
        <label for="username">ID</label>
        <input type="text" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
    </div>
        <button type="submit" class="submit_button" value="Login">로그인</button>
</form>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
    <form class="sign-form" method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="first_name">성</label>
            <input type="text" name="first_name" id="first_name"
                   value="{{ form.first_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="last_name">이름</label>
            <input type="text" name="last_name" id="last_name"
                   value="{{ form.last_name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="username">ID</label>
            <input type="text" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">Password</label>
            <input type="password" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">Password 확인</label>
            <input type="password" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="submit_button">회원가입</button>
    </form>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="sign_error_form">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="main_page">
    {% if user.is_authenticated %}
    <h1>{{ user.last_name }}님 어서와요!</h1>
    {% else %}
    <h1>환영합니다!</h1>
    {% endif %}

    <div class="explaination">
        <b>MBTIGPT</b>로 원하는 MBTI의 친구를 사귀어 보세요.
    </div>
    <br><br>

    <img src="{% static 'Component1.svg' %}" style="width:170px"/><br>
    <img src="{% static 'Component2.svg' %}" style="width:170px"/><br>
    <img src="{% static 'Component3.svg' %}" style="width:170px"/><br>
    <img src="{% static 'Component4.svg' %}" style="width:170px"/><br>
    <img src="{% static 'Component5.svg' %}" style="width:170px"/>


</div>


<div class="copyright">
    <p>&copy; 2023 KANG JOOHYEONG. All rights reserved.</p>
</div>
{% endblock %}

templates/navbar.html
{% load static %}

<header>
        <nav class="navbar">
            <div class="navbar-brand">
                <a href="{% url 'index' %}"><img src="{% static 'Component1.svg' %}" style="width:100px"/></a>
            </div>
            <ul class="nav-links">
                <li><a href="{% url 'chat:index' %}">채팅</a></li>
                {% if user.is_authenticated %}
                <li><a class="nav-link" href="{% url 'common:logout' %}">로그아웃</a></li>
                {% else %}
                <li> <a class="nav-link" href="{% url 'common:login' %}">로그인</a></li>
                {% endif %}
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </header>
    <style type="text/css">
        a:link { color:white; text-decoration: none;}
        a:visited { color: white; text-decoration: none;}
        a:hover { color: white; text-decoration: none;}
    </style>